const euLanguages = [
  'Bulgarian', // ['Bulgaria']],
  'Croatian', // ['Croatia', 'Austria']],
  'Czech', // ['Czech Republic', 'Slovakia']],
  'Danish', // ['Denmark', 'Germany']],
  'Dutch', // ['Belgium', 'Netherlands']],
  'English', // ['Ireland', 'Malta', 'United Kingdom']],
  'Estonian', // ['Estonia']],
  'Finnish', // ['Finland']],
  'French', // ['Belgium', 'France', 'Luxembourg', 'Italy']],
  'German', // ['Austria', 'Belgium', 'Germany', 'Luxembourg', 'Denmark', 'Italy', 'Poland']],
  'Greek', // ['Cyprus', 'Greece']],
  'Hungarian', // ['Hungary', 'Austria', 'Romania', 'Slovakia', 'Slovenia']],
  'Irish', // ['Ireland', 'United Kingdom']],
  'Italian', // ['Italy', 'Croatia', 'Malta', 'Slovenia']],
  'Latvian', // ['Latvia']],
  'Lithuanian', // ['Lithuania', 'Poland']],
  'Maltese', // ['Malta']],
  'Polish', // ['Poland']],
  'Portuguese', // ['Portugal']],
  'Romanian', // ['Romania']],
  'Slovak', // ['Slovakia', 'Czech Republic', 'Hungary']],
  'Slovenian', // ['Slovenia', 'Austria', 'Hungary', 'Italy']],
  'Spanish', // ['Spain']],
  'Swedish', // ['Sweden', 'Finland']],
  'Icelandic', // ['Iceland']],
  'Norwegian', // ['Norway']],
  'Moldovan', // ['Moldova']],
]
const isoLanguages = [
  ['abe', 'Abenaki', 0],
  ['gaz', 'Afaan Oromo', 8],
  ['aar', 'Afar', 6],
  ['afr', 'Afrikaans', 7],
  ['sqi', 'Albanian', 7],
  ['ami', 'Amis', 5],
  ['aud', 'Anuta', 2],
  ['arg', 'Aragonese', 4],
  ['oci', 'Aranese', 4],
  ['rup', 'Aromanian', 5],
  ['aat', 'Arvanitic (Latin)', 4],
  ['ast', 'Asturian', 6],
  ['tay', 'Atayal', 5],
  ['aym', 'Aymara', 6],
  ['azj', 'Azerbaijani', 7],
  ['bak', 'Bashkir (Latin)', 6],
  ['eus', 'Basque', 6],
  ['bel', 'Belarusian (Latin)', 7],
  ['bem', 'Bemba', 7],
  ['bik', 'Bikol', 6],
  ['bis', 'Bislama', 4],
  ['bos', 'Bosnian', 6],
  ['bre', 'Breton', 5],
  ['bul', 'Bulgarian', -1],
  ['kea', 'Cape Verdean Creole', 6],
  ['cat', 'Catalan', 7],
  ['ceb', 'Cebuano', 7],
  ['cha', 'Chamorro', 5],
  ['cbk', 'Chavacano', 6],
  ['nya', 'Chichewa', 7],
  ['cic', 'Chickasaw', 2],
  ['cim', 'Cimbrian', 3],
  ['con', 'Cofán', 3],
  ['cor', 'Cornish', 2],
  ['cos', 'Corsican', 5],
  ['mus', 'Creek', 4],
  ['crh', 'Crimean Tatar (Latin)', 6],
  ['hrv', 'Croatian', 7],
  ['ces', 'Czech', 7],
  ['dan', 'Danish', 7],
  ['aoz', 'Dawan', 6],
  ['del', 'Delaware', 0],
  ['luo', 'Dholuo', 6],
  ['dhv', 'Drehu', 4],
  ['nld', 'Dutch', 7],
  ['eng', 'English', 9],
  ['est', 'Estonian', 6],
  ['fao', 'Faroese', 5],
  ['fij', 'Fijian', 6],
  ['fil', 'Filipino', 7],
  ['fin', 'Finnish', 7],
  ['fra', 'French', 8],
  ['fry', 'Frisian', 6],
  ['fur', 'Friulian', 5],
  ['gag', 'Gagauz (Latin)', 5],
  ['glg', 'Galician', 6],
  ['gqa', 'Ganda', 6],
  ['deu', 'German', 8],
  ['kik', 'Gikuyu', 7],
  ['gni', 'Gooniyandi', 2],
  ['kal', 'Greenlandic (Kalaallisut)', 5],
  ['gcf', 'Guadeloupean Creole', 6],
  ['gwi', 'Gwich’in', 3],
  ['hat', 'Haitian Creole', 7],
  ['haa', 'Hän', 1],
  ['haw', 'Hawaiian', 4],
  ['hil', 'Hiligaynon', 7],
  ['hop', 'Hopi', 4],
  ['win', 'Hotcąk (Latin)', 2],
  ['hun', 'Hungarian', 7],
  ['isl', 'Icelandic', 5],
  ['ido', 'Ido', 2],
  ['ibo', 'Igbo', 7],
  ['ilo', 'Ilocano', 7],
  ['ind', 'Indonesian', 7],
  ['gle', 'Irish', 6],
  ['ruo', 'Istro-Romanian', 3],
  ['ita', 'Italian', 8],
  ['jam', 'Jamaican', 6],
  ['jav', 'Javanese (Latin)', 8],
  ['kgp', 'Kaingang', 4],
  ['mwp', 'Kala Lagaw Ya', 3],
  ['pam', 'Kapampangan (Latin)', 6],
  ['cak', 'Kaqchikel', 6],
  ['kaa', 'Karakalpak (Latin)', 6],
  ['krl', 'Karelian (Latin)', 5],
  ['csb', 'Kashubian', 5],
  ['kng', 'Kikongo', 7],
  ['kin', 'Kinyarwanda', 7],
  ['gil', 'Kiribati', 5],
  ['run', 'Kirundi', 7],
  ['kur', 'Kurdish (Latin)', 7],
  ['lld', 'Ladin', 4],
  ['lat', 'Latin', 0],
  ['lav', 'Latvian', 6],
  ['lit', 'Lithuanian', 7],
  ['lmo', 'Lombard', 7],
  ['ltz', 'Luxembourgish', 6],
  ['mas', 'Maasai', 6],
  ['vmw', 'Makhuwa', 6],
  ['zlm', 'Malay', 7],
  ['mlt', 'Maltese', 6],
  ['glv', 'Manx', 2],
  ['rar', 'Māori', 5],
  ['ruq', 'Megleno-Romanian', 4],
  ['ulk', 'Meriam Mir', 2],
  ['mwl', 'Mirandese', 4],
  ['moh', 'Mohawk', 4],
  ['ron', 'Moldovan', 7],
  ['moe', 'Montagnais', 4],
  ['srp', 'Montenegrin', 6],
  ['mwf', 'Murrinh-Patha', 3],
  ['nag', 'Nagamese Creole', 4],
  ['nhn', 'Nahuatl', 6],
  ['nbl', 'Ndebele', 6],
  ['nap', 'Neapolitan', 7],
  ['wyb', 'Ngiyambaa', 1],
  ['niu', 'Niuean', 4],
  ['xrg', 'Noongar', 2],
  ['nor', 'Norwegian', 7],
  ['oci', 'Occitan', 6],
  ['non', 'Old Norse', 0],
  ['acz', 'Onĕipŏt', 3],
  ['kua', 'Oshiwambo', 6],
  ['oss', 'Ossetian (Latin)', 6],
  ['plz', 'Palauan', 4],
  ['pap', 'Papiamento', 5],
  ['pms', 'Piedmontese', 6],
  ['pol', 'Polish', 8],
  ['por', 'Portuguese', 8],
  ['pot', 'Potawatomi', 2],
  ['kek', 'Q’eqchi’', 6],
  ['que', 'Quechua', 7],
  ['rar', 'Rarotongan', 5],
  ['ron', 'Romanian', 7],
  ['roh', 'Romansh', 5],
  ['roo', 'Rotokas', 4],
  ['smn', 'Sami (Inari Sami)', 2],
  ['smj', 'Sami (Lule Sami)', 3],
  ['sme', 'Sami (Northern Sami)', 4],
  ['sma', 'Sami (Southern Sami)', 3],
  ['smo', 'Samoan', 6],
  ['sag', 'Sango', 6],
  ['srm', 'Saramaccan', 4],
  ['srd', 'Sardinian', 6],
  ['gla', 'Scottish Gaelic', 5],
  ['srp', 'Serbian (Latin)', 7],
  ['sei', 'Seri', 3],
  ['crs', 'Seychellois Creole', 5],
  ['sjw', 'Shawnee', 2],
  ['sna', 'Shona', 7],
  ['scn', 'Sicilian', 7],
  ['slk', 'Slovak', 7],
  ['slv', 'Slovenian', 6],
  ['som', 'Somali', 7],
  ['dsb', 'Sorbian (Lower Sorbian)', 4],
  ['hsb', 'Sorbian (Upper Sorbian)', 5],
  ['nso', 'Sotho (Northern)', 7],
  ['sot', 'Sotho (Southern)', 7],
  ['spa', 'Spanish', 9],
  ['srn', 'Sranan', 5],
  ['sun', 'Sundanese (Latin)', 7],
  ['swa', 'Swahili', 7],
  ['ssw', 'Swazi', 6],
  ['swe', 'Swedish', 7],
  ['tgl', 'Tagalog', 7],
  ['tah', 'Tahitian', 5],
  ['tdt', 'Tetum', 6],
  ['tpi', 'Tok Pisin', 5],
  ['tkl', 'Tokelauan', 4],
  ['ton', 'Tongan', 5],
  ['lua', 'Tshiluba', 7],
  ['tso', 'Tsonga', 7],
  ['tsn', 'Tswana', 7],
  ['tum', 'Tumbuka', 6],
  ['tur', 'Turkish', 8],
  ['tuk', 'Turkmen (Latin)', 7],
  ['tvl', 'Tuvaluan', 4],
  ['tzo', 'Tzotzil', 6],
  ['uzb', 'Uzbek (Latin)', 7],
  ['vec', 'Venetian', 6],
  ['vep', 'Vepsian', 4],
  ['wls', 'Wallisian', 4],
  ['wln', 'Walloon', 6],
  ['war', 'Waray-Waray', 6],
  ['wbp', 'Warlpiri', 3],
  ['guc', 'Wayuu', 5],
  ['cym', 'Welsh', 6],
  ['wim', 'Wik-Mungkan', 3],
  ['wrh', 'Wiradjuri', 0],
  ['wol', 'Wolof', 7],
  ['xav', 'Xavante', 4],
  ['xho', 'Xhosa', 7],
  ['yap', 'Yapese', 4],
  ['yij', 'Yindjibarndi', 2],
  ['zap', 'Zapotec', 6],
  ['dje', 'Zarma', 6],
  ['diq', 'Zazaki', 6],
  ['zul', 'Zulu', 7],
  ['zun', 'Zuni', 4]
]