const unicodeTable = [
  "Control character",
  "Basic Latin",
  "Latin-1 Supplement",
  "Latin extended A",
  "Latin extended B",
  "Latin extended additional",
  "General Punctuation",
  "IPA Extentions",
  "Alphabetic Presentation Forms",
  "Combining Diacritical Marks",
  "Currency Symbols",
  "Geometric Shapes",
  "Greek and Coptic",
  "Letterlike Symbols",
  "Mathematical Operators",
  "Private Use Area",
  "Spacing Modifier Letters",
]