import { StandardFont } from 'helpers/StandardFonts/StandardFont'
import { GlyphSet, GlyphMap, widths, glyphSetOptions } from 'helpers/StandardFonts/glyphset/glyphset'

export class Symbol extends StandardFont {
  constructor() {
    super()
    this.setCharset(glyphMap, withs, charset)
    this.unitsPerEm= 1000
    this.fontName= 'Symbol'
    this.fullName= 'Symbol'
    this.familyName= 'Symbol'
    this.weight= 'Medium'
    this.italicAngle= 0
    this.isFixedPitch= 0
    this.fontBBox= [-180, -293, 1090, 1010]
    this.underlinePosition= -100
    this.underlineThickness= 50
  }
}

const charset = '\x0023456789@ABCDEFGHIPQRSTUVWXY`abcdefghipqrstuvwxyĀāĂăĄąĆćĈĉĐđĒēĔĕĖėĘęĠġĢģĤĥĦŠšŢţŤťŦŧŨũŰűŲųŴŵŶŷŸŹƀƁƂƃƄƅƆƇƈƉƐƑƒƓƔƕƖƗƘƙȀȁȂȃȄȅȆȇȈȉȐȑȒȓȔȕȖȗȘșȠȡȢȣȤȥȦȧȨȩȰȱȲȳȴȵȶȷȸȹɁɂɃɄɅɆɇɈɉɐɑɒɓɔ'

const c = [
  ' space','!exclam','∀universal','#numbersign','∃existential','%percent','&ampersand','∋suchthat','(parenleft',')parenright','∗asteriskmath','+plus',',comma','−minus','.period',
  '/slash','0zero','1one','2two','3three','4four','5five','6six','7seven','8eight','9nine',':colon',';semicolon','<less','=equal',
  '>greater','?question','≅congruent','ΑAlpha','ΒBeta','ΧChi','∆Delta','ΕEpsilon','ΦPhi','ΓGamma','ΗEta','ΙIota','ϑtheta1','ΚKappa','ΛLambda',
  'ΜMu','ΝNu','ΟOmicron','ΠPi','ΘTheta','ΡRho','ΣSigma','ΤTau','ΥUpsilon','ςsigma1','ΩOmega','ΞXi','ΨPsi','ΖZeta','[bracketleft',
  '∴therefore',']bracketright','⊥perpendicular','_underscore','radicalex','αalpha','βbeta','χchi','δdelta','εepsilon','φphi','γgamma','ηeta','ιiota','ϕphi1',
  'κkappa','λlambda','µmu','νnu','οomicron','πpi','θtheta','ρrho','σsigma','τtau','υupsilon','ϖomega1','ωomega','ξxi','ψpsi',
  'ζzeta','{braceleft','|bar','}braceright','∼similar','€Euro','ϒUpsilon1','′minute','≤lessequal','⁄fraction','∞infinity','ƒflorin','♣club','♦diamond','♥heart',
  '♠spade','↔arrowboth','←arrowleft','↑arrowup','→arrowright','↓arrowdown','°degree','±plusminus','″second','≥greaterequal','×multiply','∝proportional','∂partialdiff','•bullet','÷divide',
  '≠notequal','≡equivalence','≈approxequal','…ellipsis','arrowvertex','arrowhorizex','↵carriagereturn','ℵaleph','ℑIfraktur','ℜRfraktur','℘weierstrass','⊗circlemultiply','⊕circleplus','∅emptyset','∩intersection',
  '∪union','⊃propersuperset','⊇reflexsuperset','⊄notsubset','⊂propersubset','⊆reflexsubset','∈element','∉notelement','∠angle','∇gradient','registerserif','copyrightserif','trademarkserif','∏product','√radical',
  '⋅dotmath','¬logicalnot','∧logicaland','∨logicalor','⇔arrowdblboth','⇐arrowdblleft','⇑arrowdblup','⇒arrowdblright','⇓arrowdbldown','◊lozenge','〈angleleft','registersans','copyrightsans','trademarksans','∑summation',
  'parenlefttp','parenleftex','parenleftbt','bracketlefttp','bracketleftex','bracketleftbt','bracelefttp','braceleftmid','braceleftbt','braceex','〉angleright','∫integral','⌠integraltp','integralex','⌡integralbt',
  'parenrighttp','parenrightex','parenrightbt','bracketrighttp','bracketrightex','bracketrightbt','bracerighttp','bracerightmid','bracerightbt',
]

const glyphMap = new GlyphMap([
  ['\x00','.notdef'],
  [' ','space'],
  ['!','exclam'],
  ['∀','universal'],
  ['#','numbersign'],
  ['∃','existential'],
  ['%','percent'],
  ['&','ampersand'],
  ['∋','suchthat'],
  ['(','parenleft'],
  [')','parenright'],
  ['∗','asteriskmath'],
  ['+','plus'],
  [',','comma'],
  ['−','minus'],
  ['.','period'],
  ['/','slash'],
  ['0','zero'],
  ['1','one'],
  ['2','two'],
  ['3','three'],
  ['4','four'],
  ['5','five'],
  ['6','six'],
  ['7','seven'],
  ['8','eight'],
  ['9','nine'],
  [':','colon'],
  [';','semicolon'],
  ['<','less'],
  ['=','equal'],
  ['>','greater'],
  ['?','question'],
  ['≅','congruent'],
  ['Α','Alpha'],
  ['Β','Beta'],
  ['Χ','Chi'],
  ['∆','Delta'],
  ['Ε','Epsilon'],
  ['Φ','Phi'],
  ['Γ','Gamma'],
  ['Η','Eta'],
  ['Ι','Iota'],
  ['ϑ','theta1'],
  ['Κ','Kappa'],
  ['Λ','Lambda'],
  ['Μ','Mu'],
  ['Ν','Nu'],
  ['Ο','Omicron'],
  ['Π','Pi'],
  ['Θ','Theta'],
  ['Ρ','Rho'],
  ['Σ','Sigma'],
  ['Τ','Tau'],
  ['Υ','Upsilon'],
  ['ς','sigma1'],
  ['Ω','Omega'],
  ['Ξ','Xi'],
  ['Ψ','Psi'],
  ['Ζ','Zeta'],
  ['[','bracketleft'],
  ['∴','therefore'],
  [']','bracketright'],
  ['⊥','perpendicular'],
  ['_','underscore'],
  ['','radicalex'],
  ['α','alpha'],
  ['β','beta'],
  ['χ','chi'],
  ['δ','delta'],
  ['ε','epsilon'],
  ['φ','phi'],
  ['γ','gamma'],
  ['η','eta'],
  ['ι','iota'],
  ['ϕ','phi1'],
  ['κ','kappa'],
  ['λ','lambda'],
  ['µ','mu'],
  ['ν','nu'],
  ['ο','omicron'],
  ['π','pi'],
  ['θ','theta'],
  ['ρ','rho'],
  ['σ','sigma'],
  ['τ','tau'],
  ['υ','upsilon'],
  ['ϖ','omega1'],
  ['ω','omega'],
  ['ξ','xi'],
  ['ψ','psi'],
  ['ζ','zeta'],
  ['{','braceleft'],
  ['|','bar'],
  ['}','braceright'],
  ['∼','similar'],
  ['€','Euro'],
  ['ϒ','Upsilon1'],
  ['′','minute'],
  ['≤','lessequal'],
  ['⁄','fraction'],
  ['∞','infinity'],
  ['ƒ','florin'],
  ['♣','club'],
  ['♦','diamond'],
  ['♥','heart'],
  ['♠','spade'],
  ['↔','arrowboth'],
  ['←','arrowleft'],
  ['↑','arrowup'],
  ['→','arrowright'],
  ['↓','arrowdown'],
  ['°','degree'],
  ['±','plusminus'],
  ['″','second'],
  ['≥','greaterequal'],
  ['×','multiply'],
  ['∝','proportional'],
  ['∂','partialdiff'],
  ['•','bullet'],
  ['÷','divide'],
  ['≠','notequal'],
  ['≡','equivalence'],
  ['≈','approxequal'],
  ['…','ellipsis'],
  ['','arrowvertex'],
  ['','arrowhorizex'],
  ['↵','carriagereturn'],
  ['ℵ','aleph'],
  ['ℑ','Ifraktur'],
  ['ℜ','Rfraktur'],
  ['℘','weierstrass'],
  ['⊗','circlemultiply'],
  ['⊕','circleplus'],
  ['∅','emptyset'],
  ['∩','intersection'],
  ['∪','union'],
  ['⊃','propersuperset'],
  ['⊇','reflexsuperset'],
  ['⊄','notsubset'],
  ['⊂','propersubset'],
  ['⊆','reflexsubset'],
  ['∈','element'],
  ['∉','notelement'],
  ['∠','angle'],
  ['∇','gradient'],
  ['','registerserif'],
  ['','copyrightserif'],
  ['','trademarkserif'],
  ['∏','product'],
  ['√','radical'],
  ['⋅','dotmath'],
  ['¬','logicalnot'],
  ['∧','logicaland'],
  ['∨','logicalor'],
  ['⇔','arrowdblboth'],
  ['⇐','arrowdblleft'],
  ['⇑','arrowdblup'],
  ['⇒','arrowdblright'],
  ['⇓','arrowdbldown'],
  ['◊','lozenge'],
  ['〈','angleleft'],
  ['','registersans'],
  ['','copyrightsans'],
  ['','trademarksans'],
  ['∑','summation'],
  ['','parenlefttp'],
  ['','parenleftex'],
  ['','parenleftbt'],
  ['','bracketlefttp'],
  ['','bracketleftex'],
  ['','bracketleftbt'],
  ['','bracelefttp'],
  ['','braceleftmid'],
  ['','braceleftbt'],
  ['','braceex'],
  ['〉','angleright'],
  ['∫','integral'],
  ['⌠','integraltp'],
  ['','integralex'],
  ['⌡','integralbt'],
  ['','parenrighttp'],
  ['','parenrightex'],
  ['','parenrightbt'],
  ['','bracketrighttp'],
  ['','bracketrightex'],
  ['','bracketrightbt'],
  ['','bracerighttp'],
  ['','bracerightmid'],
  ['','bracerightbt'],
])
const withs = {
  ' ':250,'!':333,'∀':713,'#':500,'∃':549,'%':833,'&':778,'∋':439,'(':333,')':333,'∗':500,'+':549,',':250,'−':549,'.':250,
  '/':278,'0':500,'1':500,'2':500,'3':500,'4':500,'5':500,'6':500,'7':500,'8':500,'9':500,':':278,';':278,'<':549,'=':549,
  '>':549,'?':444,'≅':549,'Α':722,'Β':667,'Χ':722,'∆':612,'Ε':611,'Φ':763,'Γ':603,'Η':722,'Ι':333,'ϑ':631,'Κ':722,'Λ':686,
  'Μ':889,'Ν':722,'Ο':722,'Π':768,'Θ':741,'Ρ':556,'Σ':592,'Τ':611,'Υ':690,'ς':439,'Ω':768,'Ξ':645,'Ψ':795,'Ζ':611,'[':333,
  '∴':863,']':333,'⊥':658,'_':500,'':500,'α':631,'β':549,'χ':549,'δ':494,'ε':439,'φ':521,'γ':411,'η':603,'ι':329,'ϕ':603,
  'κ':549,'λ':549,'µ':576,'ν':521,'ο':549,'π':549,'θ':521,'ρ':549,'σ':603,'τ':439,'υ':576,'ϖ':713,'ω':686,'ξ':493,'ψ':686,
  'ζ':494,'{':480,'|':200,'}':480,'∼':549,'€':750,'ϒ':620,'′':247,'≤':549,'⁄':167,'∞':713,'ƒ':500,'♣':753,'♦':753,'♥':753,
  '♠':753,'↔':1042,'←':987,'↑':603,'→':987,'↓':603,'°':400,'±':549,'″':411,'≥':549,'×':549,'∝':713,'∂':494,'•':460,'÷':549,
  '≠':549,'≡':549,'≈':549,'…':1000,'':603,'':1000,'↵':658,'ℵ':823,'ℑ':686,'ℜ':795,'℘':987,'⊗':768,'⊕':768,'∅':823,'∩':768,
  '∪':768,'⊃':713,'⊇':713,'⊄':713,'⊂':713,'⊆':713,'∈':713,'∉':713,'∠':768,'∇':713,'':790,'':790,'':890,'∏':823,'√':549,
  '⋅':250,'¬':713,'∧':603,'∨':603,'⇔':1042,'⇐':987,'⇑':603,'⇒':987,'⇓':603,'◊':494,'〈':329,'':790,'':790,'':786,'∑':713,
  '':384,'':384,'':384,'':384,'':384,'':384,'':494,'':494,'':494,'':494,'〉':329,'∫':274,'⌠':686,'':686,'⌡':686,
  '':384,'':384,'':384,'':384,'':384,'':384,'':494,'':494,'':494,
}
